
name: Dev ECS Infrastructure Stack

on:
  workflow_run:
    workflows:
      - Common Infra Cloudformation Stack
    types:
      - completed

jobs:
  deploy:
    name: Package Cloudformation Template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'
      - name: Package Template
        working-directory: ./dev-ecs/infra
        run: |
          aws cloudformation package --template-file templates/_master.template \
                                        --s3-bucket "cloudformation-templates-ism0080" \
                                        --s3-prefix "Dev-ECS/${GITHUB_RUN_NUMBER}" \
                                        --output-template-file _master.template.packaged.json
      - name: Create or Update Stack
        run: |
          aws cloudformation deploy --template-file ./dev-ecs/infra/_master.template.packaged.json \
                                      --stack-name Dev-ECS --parameter-overrides ClusterName=DevDeploy ServerCertificateArn=${{ secrets.SERVER_CERTIFICATE_ARN }} \
                                      --capabilities CAPABILITY_IAM
