
name: Dev ECS Infrastructure Stack

on:
  workflow_run:
    workflows:
      - Common Infra Cloudformation Stack
    types:
      - completed

jobs:
  package:
    name: Package Cloudformation Template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'
      - name: Package Template
        working-directory: ./dev-ecs/infra
        run: |
          aws cloudformation package --template-file templates/_master.template \
                                        --s3-bucket "cloudformation-templates-ism0080" \
                                        --s3-prefix "Dev-ECS/${GITHUB_RUN_NUMBER}" \
                                        --output-template-file _master.template.packaged.json
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cf_template
          path: ./_master.template.packaged.json

  upload:
    name: Deploy stack to AWS
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'
      - name: Create or Update Stack
        run: |
          aws cloudformation deploy --template-file cf_template --stack-name Dev-ECS --parameter-overrides ClusterName=DevDeploy ServerCertificateArn=${{ secrets.SERVER_CERTIFICATE_ARN }} --capabilities CAPABILITY_IAM
